let Q=[],M=[],F=[],queue=[],idx=0,mode='learn',session=[],answered=false,card=0,flipped=false;
let S=JSON.parse(localStorage.getItem('az900_state')||'{"xp":0,"streak":0,"answered":{},"wrong":[],"dark":false,"unlockedMsg":{}}');
if(S.dark)document.body.classList.add('dark'); const $=id=>document.getElementById(id);
Promise.all([fetch('data/questions.json').then(r=>r.json()),fetch('data/modules.json').then(r=>r.json()),fetch('data/flashcards.json').then(r=>r.json())]).then(d=>{[Q,M,F]=d;dashboard()});
function save(){localStorage.setItem('az900_state',JSON.stringify(S))}function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id).classList.add('active')}
function pct(){return Object.keys(S.answered).length/Q.length}function stage(){let p=pct()*100;return p>=60?'Endgame':p>=35?'V3':p>=15?'V2':'V1'}function title(id){return M.find(m=>m.id==id)?.title||id}
function available(q){return (M.find(m=>m.id==q.moduleId)?.unlock||0)<=pct()*100}function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function letters(a){return a.map(i=>String.fromCharCode(65+i)).join(', ')}function same(a,b){a=[...a].sort();b=[...b].sort();return a.length==b.length&&a.every((v,i)=>v==b[i])}
function dashboard(){show('dash');let p=Math.round(pct()*100), st=stage(); $('xp').textContent='⭐ '+S.xp+' XP';$('lvl').textContent='Level '+(Math.floor(S.xp/1000)+1);$('streak').textContent='🔥 '+S.streak;$('overall').style.width=p+'%';$('overallText').textContent=Object.keys(S.answered).length+' von '+Q.length+' Fragen beantwortet ('+p+' %)';$('status').textContent='Aktuelle Freischaltung: '+st+'. V2 ab 15%, V3 ab 35%, Endgame ab 60%.';
$('mods').innerHTML=M.map(m=>{let qs=Q.map((q,i)=>[q,i]).filter(x=>x[0].moduleId==m.id),seen=qs.filter(x=>S.answered[x[1]]).length,mp=qs.length?Math.round(seen/qs.length*100):0,un=(m.unlock<=p);return `<div class="mod"><b>${un?'🔓':'🔒'} ${m.title}</b><span class="bar"><i style="width:${mp}%"></i></span><span class="pill">${seen}/${qs.length}</span></div>`}).join(''); renderSearch()}
function renderSearch(){let t=($('search')?.value||'').toLowerCase(); if(!t){$('results').innerHTML='';return} let f=Q.filter(q=>(q.question+' '+q.options.join(' ')+' '+q.explanation+' '+title(q.moduleId)).toLowerCase().includes(t)).slice(0,10);$('results').innerHTML=f.map(q=>`<div class="searchItem"><b>${title(q.moduleId)}</b><br>${q.question}<br><small>${q.tip}</small></div>`).join('')||'<p class=muted>Nichts gefunden.</p>'}
function start(m){mode=m;session=[];idx=0; if(m=='learn')queue=shuffle(Q.map((q,i)=>[q,i]).filter(x=>available(x[0])).map(x=>x[1])); else if(m=='weak')queue=shuffle(S.wrong.length?S.wrong:Q.map((q,i)=>[q,i]).filter(x=>x[0].moduleId=='governance'||x[0].level>1).map(x=>x[1])); else queue=shuffle(Q.map((q,i)=>i)).slice(0,50);show('quiz');renderQ()}
function renderQ(){answered=false;$('next').disabled=true;$('fb').style.display='none';let q=Q[queue[idx]];$('mode').textContent=mode=='learn'?'Lernmodus':mode=='weak'?'Fehlertraining':'Prüfungsmodus';$('num').textContent=`Frage ${idx+1}/${queue.length}`;$('cat').textContent=title(q.moduleId);$('lev').textContent='Level '+q.level;$('qbar').style.width=Math.round(idx/queue.length*100)+'%';$('type').textContent=q.type=='multi'?'Mehrere Antworten möglich':'Eine Antwort';$('qtext').textContent=q.question;let typ=q.type=='multi'?'checkbox':'radio';$('opts').innerHTML=q.options.map((o,i)=>`<label class=opt><input type=${typ} name=a value=${i}> ${String.fromCharCode(65+i)}) ${o}</label>`).join('')}
function sel(){return [...document.querySelectorAll('input[name=a]:checked')].map(x=>+x.value)}
function check(){if(answered)return;let s=sel();if(!s.length)return alert('Bitte Antwort auswählen 🙂');answered=true;let qi=queue[idx],q=Q[qi],ok=same(s,q.answer);session.push({qi,s,ok});S.answered[qi]=(S.answered[qi]||0)+1;if(ok){S.xp+=q.level*100;S.streak++;S.wrong=S.wrong.filter(x=>x!=qi)}else{S.streak=0;if(!S.wrong.includes(qi))S.wrong.push(qi)}save();let fb=$('fb');fb.style.display='block';fb.className=ok?'right':'wrong';fb.innerHTML=mode=='exam'?'Antwort gespeichert.':`${ok?'✅ Richtig!':'❌ Nicht ganz.'}<br><br><b>Richtig:</b> ${letters(q.answer)}<br><br>${q.explanation}<br><br><b>Merksatz:</b> ${q.tip}<br><small>${q.source}</small>`;$('next').disabled=false}
function next(){if(idx<queue.length-1){idx++;renderQ()}else finish()}
function finish(){show('res');let c=session.filter(x=>x.ok).length,p=Math.round(c/session.length*100);$('score').textContent=`${c}/${session.length} (${p}%)`;$('resText').textContent=p>=85?'Sehr stark!':p>=70?'Solide, Fehlertraining lohnt sich.':'Starte am besten Fehlertraining.';$('review').innerHTML=session.map((x,n)=>{let q=Q[x.qi];return `<div class=review><b>${n+1}. ${title(q.moduleId)}</b> ${x.ok?'✅':'❌'}<br>${q.question}<br><small>Deine Antwort: ${letters(x.s)} | Richtig: ${letters(q.answer)}</small><br>${q.explanation}</div>`}).join('')}
function showCards(){show('cards');card=0;renderCard()}function renderCard(){flipped=false;let c=F[card%F.length];$('cardMeta').textContent=`${card+1}/${F.length} · ${title(c.moduleId)} · Karte anklicken`;$('card').textContent=c.front}function flip(){let c=F[card%F.length];flipped=!flipped;$('card').textContent=flipped?c.back:c.front}function nextCard(){card=(card+1)%F.length;renderCard()}
$('themeBtn').onclick=()=>{S.dark=!S.dark;document.body.classList.toggle('dark');save()};$('resetBtn').onclick=()=>{if(confirm('Fortschritt löschen?')){S={xp:0,streak:0,answered:{},wrong:[],dark:S.dark,unlockedMsg:{}};save();dashboard()}};